[tools]

# Core dependencies
go = "1.22.7"
just = "1.38.0"

# Go dependencies
"go:github.com/ethereum/go-ethereum/cmd/abigen" = "1.15.2"
"ubi:golangci/golangci-lint" = "v1.63.4"
"ubi:kurtosis-tech/kurtosis-cli-release-artifacts[exe=kurtosis]" = "1.4.4"

# Foundry dependencies
# Foundry is a special case because it supplies multiple binaries at the same
# GitHub release, so we need to use the aliasing trick to get mise to not error
# The git ref here should be on the `stable` branch.
forge = "v1.0.0"
cast = "v1.0.0"
anvil = "v1.0.0"

[alias]
forge = "ubi:foundry-rs/foundry[exe=forge]"
cast = "ubi:foundry-rs/foundry[exe=cast]"
anvil = "ubi:foundry-rs/foundry[exe=anvil]"

[settings]
experimental = true